<Project Sdk="Microsoft.NET.Sdk">
	
	<PropertyGroup>
		<Nullable>disable</Nullable>
		<NoWarn>$(NoWarn);CS8625;CS8603</NoWarn>
		<TargetFrameworks>$(CoreVersion);$(CoreVersion)-android</TargetFrameworks>
	</PropertyGroup>
	
	<ItemGroup Condition="'$(OpenGL)' == 'ES'">
		<PackageReference Include="Silk.NET.OpenGLES" Version="2.23.0" />
		<PackageReference Include="Silk.NET.OpenGLES.Extensions.EXT" Version="2.23.0" />
	</ItemGroup>

	<ItemGroup Condition="'$(OpenGL)' == ''">
		<PackageReference Include="Silk.NET.OpenGL" Version="2.23.0" />
	</ItemGroup>



</Project>
