// Avatar SDK runtime version file
// @generated on 09/04/2025, at 20:48:29 UTC from AndroidManifest.xml
//
// DO NOT MODIFY THIS FILE BY HAND, IT IS AUTOGENERATED
using System;
using System.Runtime.InteropServices;

namespace Oculus.Avatar2
{
    public static partial class AvatarSDKVersion
    {
        public const UInt32 AVATAR2_RELEASE_VERSION = 40;
        public const UInt32 AVATAR2_HOTFIX_VERSION = 0;
        public const UInt32 AVATAR2_EXPERIMENTATION_VERSION = 0;
        public const UInt32 AVATAR2_BETA_VERSION = 24;
        public const UInt32 AVATAR2_ALPHA_VERSION = 4;
        static public FBVersionNumber CurrentVersion()
        {
            FBVersionNumber versionNumber;
            versionNumber.releaseVersion = AVATAR2_RELEASE_VERSION;
            versionNumber.hotfixVersion = AVATAR2_HOTFIX_VERSION;
            versionNumber.experimentationVersion = AVATAR2_EXPERIMENTATION_VERSION;
            versionNumber.betaVersion = AVATAR2_BETA_VERSION;
            versionNumber.alphaVersion = AVATAR2_ALPHA_VERSION;
            return versionNumber;
        }
    }
}
