<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(CoreVersion);$(CoreVersion)-android</TargetFrameworks>
		<NativeFolder>Release</NativeFolder>
	</PropertyGroup>


	<ItemGroup Condition="'$(IsAndroid)' == 'false'">
		
		<Content Include="..\Draco.Native\bin\$(NativePlatform)\$(NativeFolder)\*" CopyToOutputDirectory="PreserveNewest" UseLink="True" Visible="False" Link="%(Filename)%(Extension)" />
	
	</ItemGroup>

	<ItemGroup Condition="'$(IsAndroid)' == 'true'">
		<AndroidNativeLibrary Abi="arm64-v8a" Include="$(NativeLibsDir)draco-native\android-arm64\*.so" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\third-party\glTF-CSharp-Loader\glTFLoader\glTFLoader.csproj" />
		<ProjectReference Include="..\Draco.Native\Draco.Native.vcxproj" />
		<ProjectReference Include="..\XrEngine.Animation\XrEngine.Animation.csproj" />
		<ProjectReference Include="..\XrEngine.Core\XrEngine.Core.csproj" />
	</ItemGroup>

</Project>
