<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(CoreVersion);$(CoreVersion)-android</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Silk.NET.Vulkan" Version="2.23.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\OpenXr.Framework\OpenXr.Framework.csproj" />
	</ItemGroup>

	<ItemGroup Condition="'$(OpenGL)' == 'ES'">
		<PackageReference Include="Silk.NET.OpenGLES" Version="2.23.0" />
	</ItemGroup>

	<ItemGroup Condition="'$(OpenGL)' == ''">
		<PackageReference Include="Silk.NET.OpenGL" Version="2.23.0" />
	</ItemGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Debug'">
		<DefineConstants>$(DefineConstants);ANGLE_DEBUG</DefineConstants>
	</PropertyGroup>

	<ItemGroup Condition="'$(IsAndroid)' == 'false' and '$(UseAngle)' == 'true' ">

		<Content Visible="false"
			Include="$(NativeLibsDir)angle/win-x64/*"
			CopyToOutputDirectory="PreserveNewest"
			Link="%(Filename)%(Extension)"
			UseLink="True" />

		<Content Visible="false"
			Include="$(NativeLibsDir)angle/win-x64/angledata/*"
			CopyToOutputDirectory="PreserveNewest"
			Link="angledata/%(Filename)%(Extension)"
			UseLink="True" />

	</ItemGroup>

	<ItemGroup Condition="'$(IsAndroid)' == 'true'">
		<AndroidNativeLibrary Include="$(NativeLibsDir)angle/android-arm64/*" Abi="arm64-v8a" />
	</ItemGroup>

</Project>
