<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(CoreVersion)-$(WinVersion);$(CoreVersion)-android</TargetFrameworks>
		<SingleProject>true</SingleProject>
	</PropertyGroup>



	<ItemGroup>
    <ProjectReference Include="..\XrEngine.Devices\XrEngine.Devices.csproj" />
    <ProjectReference Include="..\XrEngine.OpenXr\XrEngine.OpenXr.csproj" />
  </ItemGroup>



	<ItemGroup>
	  <Folder Include="Objects\" />
	</ItemGroup>

</Project>
