precision highp imageCube;
precision highp int;

layout(local_size_x=16, local_size_y=16, local_size_z=1) in;

#include "ibl_common.glsl"

const uint NumSamples = SAMPLE_COUNT;

layout(binding=0) uniform samplerCube inputTexture;
layout(binding=0, rgba16f) restrict writeonly uniform imageCube outputTexture;
uniform float roughness;

void main(void)
{
	ivec2 outputSize = imageSize(outputTexture);
	if(gl_GlobalInvocationID.x >= uint(outputSize.x) || gl_GlobalInvocationID.y >= uint(outputSize.y))
		return;

	vec2 inputSize = vec2(textureSize(inputTexture, 0));
	float wt = 4.0 * PI / (6.0 * inputSize.x * inputSize.y);
	vec3 N = getSamplingVector(outputSize, gl_GlobalInvocationID.z);
	vec3 Lo = N;
	vec3 S, T;
	computeBasisVectors(N, S, T);

	vec3 color = vec3(0.0);
	float weight = 0.0;

	for(uint i=0u; i<NumSamples; ++i)
	{
		vec2 u = sampleHammersley(i, NumSamples);
		vec3 Lh = tangentToWorld(sampleCharlie(u.x, u.y, roughness), N, S, T);
		vec3 Li = 2.0 * dot(Lo, Lh) * Lh - Lo;
		float cosLi = dot(N, Li);

		if(cosLi > 0.0)
		{
			float cosLh = max(dot(N, Lh), 0.0);
			float pdf = ndfCharlie(cosLh, roughness) * 0.25;
			float ws = 1.0 / (float(NumSamples) * pdf);
			float mipLevel = max(0.5 * log2(ws / wt) + 1.0, 0.0);

			color += textureLod(inputTexture, Li, mipLevel).rgb * cosLi;
			weight += cosLi;
		}
	}

	if(weight > 0.0)
		color /= weight;

	imageStore(outputTexture, ivec3(gl_GlobalInvocationID), vec4(color, 1.0));
}
