layout(local_size_x=16, local_size_y=16, local_size_z=1) in;

precision highp imageCube;
precision highp int;

#include "ibl_common.glsl"

layout(binding=0) uniform sampler2D inputTexture;
layout(binding=0, rgba16f) restrict writeonly uniform imageCube outputTexture;

void main(void)
{
	ivec2 outputSize = imageSize(outputTexture);
	if(gl_GlobalInvocationID.x >= uint(outputSize.x) || gl_GlobalInvocationID.y >= uint(outputSize.y))
		return;

	vec3 v = getSamplingVector(outputSize, gl_GlobalInvocationID.z);
	float phi = atan(v.x, v.z);
	float theta = acos(v.y);
	vec4 color = texture(inputTexture, vec2((phi + PI) / TwoPI, theta / PI));

	imageStore(outputTexture, ivec3(gl_GlobalInvocationID), color);
}
