precision highp imageCube;
precision highp int;

layout(local_size_x=16, local_size_y=16, local_size_z=1) in;

#include "ibl_common.glsl"

const uint NumSamples = SAMPLE_COUNT;

layout(binding=0) uniform samplerCube inputTexture;
layout(binding=0, rgba16f) restrict writeonly uniform imageCube outputTexture;

void main(void)
{
	ivec2 outputSize = imageSize(outputTexture);
	if(gl_GlobalInvocationID.x >= uint(outputSize.x) || gl_GlobalInvocationID.y >= uint(outputSize.y))
		return;

	vec3 N = getSamplingVector(outputSize, gl_GlobalInvocationID.z);
	vec3 S, T;
	computeBasisVectors(N, S, T);

	vec3 irradiance = vec3(0);

	for(uint i=0u; i<NumSamples; ++i)
	{
		vec2 u = sampleHammersley(i, NumSamples);
		vec3 Li = tangentToWorld(sampleHemisphere(u.x, u.y), N, S, T);
		float cosTheta = max(0.0, dot(Li, N));

		irradiance += 2.0 * textureLod(inputTexture, Li, 0.0).rgb * cosTheta;
	}

	irradiance /= vec3(NumSamples);

	imageStore(outputTexture, ivec3(gl_GlobalInvocationID), vec4(irradiance, 1.0));
}
