layout(local_size_x=16, local_size_y=16, local_size_z=1) in;

precision highp image2D;
precision highp int;

#include "ibl_common.glsl"

const uint NumSamples = SAMPLE_COUNT;
const float BrdfEpsilon = 0.001;

layout(binding=0, rgba16f) restrict writeonly uniform image2D LUT;

void main(void)
{
	ivec2 outputSize = imageSize(LUT);
	if(gl_GlobalInvocationID.x >= uint(outputSize.x) || gl_GlobalInvocationID.y >= uint(outputSize.y))
		return;

	float cosLo = float(gl_GlobalInvocationID.x) / float(outputSize.x);
	float roughness = float(gl_GlobalInvocationID.y) / float(outputSize.y);
	cosLo = max(cosLo, BrdfEpsilon);

	vec3 Lo = vec3(sqrt(1.0 - cosLo*cosLo), 0.0, cosLo);
	float DFG1 = 0.0;
	float DFG2 = 0.0;

	for(uint i=0u; i<NumSamples; ++i)
	{
		vec2 u = sampleHammersley(i, NumSamples);
		vec3 Lh = sampleGGX(u.x, u.y, roughness);
		vec3 Li = 2.0 * dot(Lo, Lh) * Lh - Lo;
		float cosLi = Li.z;
		float cosLh = Lh.z;
		float cosLoLh = max(dot(Lo, Lh), 0.0);

		if(cosLi > 0.0)
		{
			float G = gaSchlickGGX_IBL(cosLi, cosLo, roughness);
			float Gv = G * cosLoLh / (cosLh * cosLo);
			float Fc = pow(1.0 - cosLoLh, 5.0);

			DFG1 += (1.0 - Fc) * Gv;
			DFG2 += Fc * Gv;
		}
	}

	imageStore(LUT, ivec2(gl_GlobalInvocationID), vec4(DFG1, DFG2, 0.0, 0.0) / float(NumSamples));
}
