<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(CoreVersion)-$(WinVersion);$(CoreVersion)-android</TargetFrameworks>
	</PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Framework\OpenAl.Framework\OpenAl.Framework.csproj" />
    <ProjectReference Include="..\Fftw\Fftw.csproj" />
    <ProjectReference Include="..\Sfizz\Sfizz.csproj" />
    <ProjectReference Include="..\XrEngine.Audio\XrEngine.Audio.csproj" />
    <ProjectReference Include="..\XrEngine.Devices\XrEngine.Devices.csproj" />
  </ItemGroup>

</Project>
