<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>

	</PropertyGroup>
	<ItemGroup Condition="'$(IsAndroid)' == 'false'">

		<Content 
			Include="$(NativeLibsDir)libtiff\win-x64\*.dll" 
			CopyToOutputDirectory="PreserveNewest" 
			UseLink="True"
			Link="%(Filename)%(Extension)" />

	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="DotSpatial.Projections" Version="4.0.656" />
	  <PackageReference Include="ProjNET4GeoAPI" Version="1.4.1" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\XrEngine.Core\XrEngine.Core.csproj" />
	</ItemGroup>
</Project>
