#include "./uniforms_comp.glsl"

layout(local_size_x = 8, local_size_y = 8) in;

// Array layers:
//
//   0 = dry paint
//   1 = wet paint
//
// Each texel stores:
//
//   rgb = color * density
//   a   = density
layout(rgba16f, binding = 1) uniform highp image2D uWetPaint;
layout(rgba16f, binding = 2) uniform highp image2D uDryPaint;

// Incoming density texture.
// Only R is used.
layout(binding = 0) uniform highp sampler2D uIncomingDensity;

void main()
{
    ivec2 p = ivec2(gl_GlobalInvocationID.xy);

    if (any(greaterThanEqual(p, CanvasSize)))
        return;

    vec4 dry = imageLoad(uDryPaint, p);
    vec4 wet = imageLoad(uWetPaint, p);

    float incomingDensity =
        texelFetch(uIncomingDensity, p, 0).r * PaintColor.a;

    vec4 incoming = vec4(
        PaintColor.rgb * incomingDensity,
        incomingDensity
    );

    // Add new paint into the wet layer.
    wet += incoming;

    if (wet.a > EPS)
    {
        float deltaD = min(wet.a, DryRate * DeltaTime);

        vec3 pureWet = wet.rgb / wet.a;
        vec3 pureDry = UnitColor(dry);

        float covOld = min(wet.a, 1.0);
        float covNew = min(wet.a - deltaD, 1.0);

        float activeDelta = covOld - covNew;

        if (activeDelta > 0.0)
        {
            pureDry =
                (
                    pureDry * (1.0 - covOld) +
                    pureWet * activeDelta
                ) / max(1.0 - covNew, EPS);
        }

        // Move density from wet to dry.
        // Total density is conserved:
        //
        //   old dry.a + old wet.a == new dry.a + new wet.a
        wet.a -= deltaD;
        wet.rgb = pureWet * wet.a;

        dry.a += deltaD;
        dry.rgb = pureDry * dry.a;
    }
    else
    {
        wet = vec4(0.0);
    }

    imageStore(uDryPaint, p, dry);
    imageStore(uWetPaint, p, wet);
}