<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>$(CoreVersion)-$(WinVersion);</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="stereo.js" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="stereo.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CefSharp.Common.NETCore" Version="147.0.100" />
    <PackageReference Include="CefSharp.OffScreen.NETCore" Version="147.0.100" />
    <PackageReference Include="Silk.NET.Direct3D11" Version="2.23.0" />
    <PackageReference Include="Silk.NET.OpenGL" Version="2.23.0" />
    <PackageReference Include="Silk.NET.WGL" Version="2.23.0" />
    <PackageReference Include="Silk.NET.WGL.Extensions.NV" Version="2.23.0" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XrEngine.UI.Web\XrEngine.UI.Web.csproj" />
  </ItemGroup>


</Project>
