<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(CoreVersion)-android</TargetFrameworks>
		<SupportedOSPlatformVersion>$(AndroidPlatform)</SupportedOSPlatformVersion>
	</PropertyGroup>

	<Import Project="..\..\AspNetCoreMini.props" />

	<ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.Logging" Version="$(MsExtVersion)" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Framework\OpenXr.Framework.Android\OpenXr.Framework.Android.csproj" />
	  <ProjectReference Include="..\XrWebLink\XrWebLink.csproj" />
	</ItemGroup>


</Project>
