<Project Sdk="Microsoft.NET.Sdk">
	
	<PropertyGroup>
		<TargetFrameworks>$(CoreVersion);$(CoreVersion)-android</TargetFrameworks>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<IsTrimmable>false</IsTrimmable>
		<Nullable>disable</Nullable>
		<Description>Meta Horizon Platform SDK 205 and Avatar SDK 40.0.1 native bindings for .NET, without Unity.</Description>
	</PropertyGroup>

	<PropertyGroup Condition="'$(IsAndroid)' == 'true'">
		<AndroidManifest>Properties\AndroidManifest.xml</AndroidManifest>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

	<ItemGroup Condition="'$(IsAndroid)' == 'false'">
		<Content Include="Native\win-x64\*.dll" Visible="False" UseLink="True" Link="%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

	<ItemGroup Condition="'$(IsAndroid)' == 'true'"> 
		<AndroidNativeLibrary Include="Native\android-arm64\*.so" Abi="arm64-v8a" />
		<TrimmerRootAssembly Include="Oculus.Platform" />
	</ItemGroup>
</Project>
