using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace XrEngine.Generator
{
    [Generator]
    public sealed class NotifyChangedGenerator : IIncrementalGenerator
    {
        private const string AttributeMetadataName = "XrEngine.NotifyAttribute";
        private const string DefaultChangeType = "global::XrEngine.ChangeType.Material";

        private static readonly SymbolDisplayFormat TypeDisplayFormat =
            SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
                SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions |
                SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var properties = context.SyntaxProvider
                .CreateSyntaxProvider(
                    static (node, _) => IsCandidate(node),
                    static (ctx, _) => GetProperty(ctx))
                .Where(static p => p != null);

            var source = context.CompilationProvider.Combine(properties.Collect());

            context.RegisterSourceOutput(source, static (spc, data) =>
            {
                var compilation = data.Left;
                var props = data.Right;

                var attrType = compilation.GetTypeByMetadataName(AttributeMetadataName);
                if (attrType == null)
                    return;

                var byType = new Dictionary<INamedTypeSymbol, List<IPropertySymbol>>(SymbolEqualityComparer.Default);

                foreach (var prop in props)
                {
                    if (prop == null)
                        continue;

                    if (!HasAttribute(prop, attrType))
                        continue;

                    if (!IsValidPartialProperty(prop))
                        continue;

                    var type = prop.ContainingType;

                    if (!byType.TryGetValue(type, out var list))
                    {
                        list = new List<IPropertySymbol>();
                        byType.Add(type, list);
                    }

                    list.Add(prop);
                }

                foreach (var pair in byType)
                {
                    var text = GenerateType(pair.Key, pair.Value);

                    var hint = pair.Key.ToDisplayString()
                        .Replace(".", "_")
                        .Replace("+", "_") + ".Notify.g.cs";

                    spc.AddSource(hint, text);
                }
            });
        }

        private static bool IsCandidate(SyntaxNode node)
        {
            if (node is not PropertyDeclarationSyntax prop)
                return false;

            if (prop.AttributeLists.Count == 0)
                return false;

            return prop.Modifiers.Any(m => m.ValueText == "partial");
        }

        private static IPropertySymbol? GetProperty(GeneratorSyntaxContext context)
        {
            var prop = (PropertyDeclarationSyntax)context.Node;
            return context.SemanticModel.GetDeclaredSymbol(prop) as IPropertySymbol;
        }

        private static bool HasAttribute(IPropertySymbol prop, INamedTypeSymbol attrType)
        {
            foreach (var attr in prop.GetAttributes())
            {
                if (SymbolEqualityComparer.Default.Equals(attr.AttributeClass, attrType))
                    return true;
            }

            return false;
        }

        private static bool IsValidPartialProperty(IPropertySymbol prop)
        {
            if (prop.IsStatic)
                return false;

            if (prop.IsIndexer)
                return false;

            if (prop.GetMethod == null || prop.SetMethod == null)
                return false;

            return true;
        }

        private static string GenerateType(INamedTypeSymbol type, List<IPropertySymbol> properties)
        {
            var ns = type.ContainingNamespace.IsGlobalNamespace
                ? null
                : type.ContainingNamespace.ToDisplayString();



            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();

            if (ns != null)
            {
                sb.Append("namespace ").Append(ns).AppendLine();
                sb.AppendLine("{");
            }

            AppendContainingTypesStart(sb, type);

            sb.Append("partial ")
              .Append(GetTypeKind(type))
              .Append(' ')
              .Append(GetTypeName(type))
              .AppendLine();

            sb.AppendLine("{");

            foreach (var prop in properties.OrderBy(p => p.Name))
                GenerateProperty(sb, prop);

            sb.AppendLine("}");

            AppendContainingTypesEnd(sb, type);

            if (ns != null)
                sb.AppendLine("}");

            return sb.ToString();
        }

        private static void GenerateProperty(StringBuilder sb, IPropertySymbol prop)
        {
            var propName = prop.Name;
            var fieldName = MakeFieldName(propName);
            var typeName = prop.Type.ToDisplayString(TypeDisplayFormat);
            var requiresNullForgivingInitializer =
                prop.Type.IsReferenceType &&
                prop.NullableAnnotation == NullableAnnotation.NotAnnotated;
            var accessibility = GetAccessibility(prop.DeclaredAccessibility);
            var changeType = GetChangeType(prop);

            sb.Append("    private ")
              .Append(typeName)
              .Append(' ')
              .Append(fieldName);

            if (requiresNullForgivingInitializer)
                sb.Append(" = default!");

            sb.AppendLine(";");

            sb.AppendLine();

            sb.Append("    ")
              .Append(accessibility)
              .Append(" partial ")
              .Append(typeName)
              .Append(' ')
              .Append(propName)
              .AppendLine();

            sb.AppendLine("    {");

            sb.Append("        get => ")
              .Append(fieldName)
              .AppendLine(";");

            sb.AppendLine("        set");
            sb.AppendLine("        {");

            sb.Append("            if (EqualityComparer<")
              .Append(typeName)
              .Append(">.Default.Equals(")
              .Append(fieldName)
              .AppendLine(", value))");

            sb.AppendLine("                return;");
            sb.AppendLine();

            sb.Append("            ")
              .Append(fieldName)
              .AppendLine(" = value;");

            sb.Append("            NotifyChanged(")
              .Append(changeType)
              .AppendLine(");");

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private static string GetChangeType(IPropertySymbol prop)
        {
            var attr = prop.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == AttributeMetadataName);

            if (attr == null || attr.ConstructorArguments.Length == 0)
                return DefaultChangeType;

            var arg = attr.ConstructorArguments[0];

            if (arg.Type is not INamedTypeSymbol enumType || enumType.TypeKind != TypeKind.Enum)
                return DefaultChangeType;

            var enumTypeName = enumType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            foreach (var member in enumType.GetMembers().OfType<IFieldSymbol>())
            {
                if (!member.HasConstantValue)
                    continue;

                if (Equals(member.ConstantValue, arg.Value))
                    return enumTypeName + "." + member.Name;
            }

            return "(" + enumTypeName + ")" +
                   Convert.ToString(arg.Value, System.Globalization.CultureInfo.InvariantCulture);
        }

        private static string MakeFieldName(string propertyName)
        {
            if (string.IsNullOrEmpty(propertyName))
                return "_value";

            return "_" + char.ToLowerInvariant(propertyName[0]) + propertyName.Substring(1);
        }

        private static string GetAccessibility(Accessibility accessibility)
        {
            return accessibility switch
            {
                Accessibility.Public => "public",
                Accessibility.Internal => "internal",
                Accessibility.Protected => "protected",
                Accessibility.ProtectedAndInternal => "private protected",
                Accessibility.ProtectedOrInternal => "protected internal",
                Accessibility.Private => "private",
                _ => "public"
            };
        }

        private static string GetTypeKind(INamedTypeSymbol type)
        {
            return type.TypeKind switch
            {
                TypeKind.Struct => "struct",
                TypeKind.Interface => "interface",
                _ => "class"
            };
        }

        private static string GetTypeName(INamedTypeSymbol type)
        {
            if (type.TypeParameters.Length == 0)
                return type.Name;

            return type.Name + "<" + string.Join(", ", type.TypeParameters.Select(t => t.Name)) + ">";
        }

        private static void AppendContainingTypesStart(StringBuilder sb, INamedTypeSymbol type)
        {
            var containingTypes = new Stack<INamedTypeSymbol>();

            var cur = type.ContainingType;
            while (cur != null)
            {
                containingTypes.Push(cur);
                cur = cur.ContainingType;
            }

            while (containingTypes.Count > 0)
            {
                var t = containingTypes.Pop();

                sb.Append("partial ")
                  .Append(GetTypeKind(t))
                  .Append(' ')
                  .Append(GetTypeName(t))
                  .AppendLine();

                sb.AppendLine("{");
            }
        }

        private static void AppendContainingTypesEnd(StringBuilder sb, INamedTypeSymbol type)
        {
            var cur = type.ContainingType;
            while (cur != null)
            {
                sb.AppendLine("}");
                cur = cur.ContainingType;
            }
        }
    }
}