<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(CoreVersion);$(CoreVersion)-android</TargetFrameworks>
		<NativeFolder>Release</NativeFolder>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\third-party\etcpak\EtcPack.vcxproj" />
		<ProjectReference Include="..\XrEngine.Core\XrEngine.Core.csproj" />
	</ItemGroup>

	<ItemGroup Condition="'$(IsAndroid)' == 'false'">

		<Content Include="..\..\..\third-party\etcpak\bin\$(NativePlatform)\$(NativeFolder)\*" 
				 CopyToOutputDirectory="PreserveNewest" 
				 UseLink="True"
				 Visible="False"
				 Link="%(Filename)%(Extension)" />
		
		<Content Include="..\..\..\libs\astcencoder-native\win-x64\*" 
				 CopyToOutputDirectory="PreserveNewest" 
				 UseLink="True"
				 Visible="False"
				 Link="%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup Condition="'$(IsAndroid)' == 'true'">
		<AndroidNativeLibrary Abi="arm64-v8a" Include="..\..\..\libs\etcpack\android-arm64\*.so" />
		<AndroidNativeLibrary Abi="arm64-v8a" Include="..\..\..\libs\astcencoder-native\android-arm64\*.so" />
	</ItemGroup>
</Project>
