<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Shaders\*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XrEngine.OpenGL\XrEngine.OpenGL.csproj" />
    <ProjectReference Include="..\XrEngine.UI\XrEngine.UI.csproj" />
  </ItemGroup>

</Project>
